sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKkDruLBS9zQd7WGBMD
    access-key-secret: i0wHPuBlQ9gZSARlzKdN6LEE0FaVJJ
    bucket-name: sky-take-out-demo00

